import React, { useId, useState } from "react";
import "./wortlauf.css";

const SOURCE = "FSA-handout (old).pdf";
const ROOT = "G:/Meine Ablage/01_Studium/DHBW Mosbach/Formale Sprachen & Automaten/";
const transition = [[0, 1], [1, 2], [2, 2]];
const steps = ["Überblick", "Einstieg", "Verstehen", "Quiz", "Anwenden", "Ohne Hilfe", "Rückblick"];
function run(word) {
  return [...word].reduce((path, char) => [...path, transition[path[path.length - 1]][char === "a" ? 0 : 1]], [0]);
}
function Cite({ pages }) {
  return <p className="wl-source">Quelle: {SOURCE}, PDF-S. {pages}.</p>;
}
function Diagram({ current }) {
  const arrowId = useId();
  return <svg viewBox="0 0 640 175" role="img" aria-label={`Automat: Start 0, Endzustand 1. Bei b von 0 nach 1 und von 1 nach 2; a bleibt jeweils im Zustand. In 2 bleiben a und b.${current !== undefined ? ` Aktuell Zustand ${current}.` : ""}`}>
    <defs><marker id={arrowId} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#91a9bc" /></marker></defs>
    <g stroke="#91a9bc" strokeWidth="2" fill="none" markerEnd={`url(#${arrowId})`}><path d="M25 100 H83"/><path d="M157 100 H283"/><path d="M357 100 H483"/>
      {[120, 320, 520].map(x => <path key={x} d={`M${x-21} 72 C${x-60} 5 ${x+60} 5 ${x+21} 72`}/>)}</g>
    {[0, 1, 2].map((q) => <g key={q}><circle cx={120+q*200} cy="100" r="36" fill={current === q ? "#83efc5" : "#152b3a"} stroke={current === q ? "#83efc5" : "#91a9bc"} strokeWidth="2"/>{q === 1 && <circle cx="320" cy="100" r="30" fill="none" stroke={current === 1 ? "#10251f" : "#91a9bc"}/>}<text x={120+q*200} y="107" textAnchor="middle" fill={current === q ? "#10251f" : "#e9f0f5"} fontSize="23">{q}</text></g>)}
    <g fill="#c1d0da" fontSize="18" textAnchor="middle"><text x="120" y="25">a</text><text x="320" y="25">a</text><text x="520" y="25">a, b</text><text x="220" y="88">b</text><text x="420" y="88">b</text><text x="120" y="163">Start</text><text x="320" y="163">akzeptierend</text><text x="520" y="163">Fangzustand</text></g>
  </svg>;
}
function Machine() {
  return <><Diagram/><div className="wl-table"><table><caption>Gegeben: Q = {"{0, 1, 2}"}, Σ = {"{a, b}"}, Start 0, F = {"{1}"}</caption><thead><tr><th>Zustand</th><th>Zeichen a</th><th>Zeichen b</th></tr></thead><tbody>{transition.map((row, q) => <tr key={q}><th>{q === 0 ? "→ 0" : q === 1 ? "◎ 1" : "2"}</th>{row.map((v, i) => <td key={i}>{v}</td>)}</tr>)}</tbody></table></div></>;
}

function Exercise({ word, independent, onRecord, onNext }) {
  const path = run(word);
  const [answer, setAnswer] = useState("");
  const [verdict, setVerdict] = useState("");
  const [result, setResult] = useState("");
  const [diagnosis, setDiagnosis] = useState("");
  const [level, setLevel] = useState(0);
  const [help, setHelp] = useState(false);
  const [attempts, setAttempts] = useState(0);
  const [copied, setCopied] = useState(false);
  const prefix = word.slice(0, 2);
  function check() {
    const correct = answer === String(path[path.length - 1]) && verdict === (path[path.length - 1] === 1 ? "ja" : "nein");
    setAttempts(n => n + 1);
    setResult(correct ? "correct" : "wrong");
    if (correct) onRecord({ word, attempts: attempts + 1, help: help || level > 0 || diagnosis !== "", independent });
  }
  const support = !independent || help;
  return <>
    <div className="wl-eyebrow">{independent ? "TRANSFER · ZETTEL WEGLEGEN" : "EIGENE ANWENDUNG"}</div>
    <h2>Was macht der Automat mit <span className="wl-word">{word}</span>?</h2>
    <p>{independent ? "Löse zuerst ohne Cheat Sheet. Diagramm und Tabelle gehören zur Aufgabenstellung. Falls du festhängst, kannst du Hilfe anfordern; der Versuch zählt dann als unterstützt." : "Verfolge das Wort selbst von links nach rechts. Notiere die Zustandsfolge auf Papier, bevor du antwortest."}</p>
    <Machine/><Cite pages="69–72"/><p className="wl-muted">Eigenes Übungswort am Automaten aus dem Skript.</p>
    <div className="wl-fields"><label>Zustand nach dem ganzen Wort<select value={answer} onChange={e => {setAnswer(e.target.value); setResult("");}}><option value="">Bitte wählen</option>{[0,1,2].map(q => <option key={q}>{q}</option>)}</select></label><label>Wird das Wort akzeptiert?<select value={verdict} onChange={e => {setVerdict(e.target.value); setResult("");}}><option value="">Bitte wählen</option><option value="ja">Ja</option><option value="nein">Nein</option></select></label></div>
    <button className="wl-primary" disabled={answer === "" || verdict === "" || result === "correct"} onClick={check}>Antwort prüfen</button>
    <div aria-live="polite">
      {result === "correct" && <div className="wl-feedback"><strong>Richtig gelöst.</strong> Endzustand des Laufs: {answer}; {verdict === "ja" ? "1 ∈ F, also akzeptiert." : `${answer} ∉ F, also verworfen.`} {support && (help || level > 0 || diagnosis) ? "Du hast Unterstützung verwendet." : "Ohne aufgerufene Hilfe."}<p>Beobachtung für dieses Wort; noch kein Beleg, dass du alle Automaten beherrschst.</p><button onClick={onNext}>Nächste Aufgabe →</button></div>}
      {result === "wrong" && <div className="wl-feedback wl-warning"><strong>Noch nicht passend.</strong> Wir prüfen erst einen Zwischenschritt, bevor wir eine Fehlerursache vermuten.
        {independent && !help ? <p>Versuche es erneut oder fordere die Diagnose an.</p> : <><p>In welchem Zustand steht der Automat nach dem Präfix <b>{prefix}</b>?</p><div className="wl-actions">{[0,1,2].map(q => <button key={q} onClick={() => setDiagnosis(String(q))}>Nach {prefix}: {q}</button>)}<button onClick={() => {setDiagnosis("none"); setLevel(1);}}>Kein Ansatz</button></div></>}
      </div>}
      {support && diagnosis && <div className="wl-feedback">{diagnosis === "none" ? `Beginne in 0. Das erste Zeichen ist ${word[0]}; die Tabelle führt dich nach ${path[1]}. Markiere das gelesene Zeichen und lies erst dann weiter.` : Number(diagnosis) === path[2] ? `Der Zwischenschritt stimmt. Damit ist noch keine Fehlerursache belegt. Verarbeite jetzt den Rest „${word.slice(2)}“ und prüfe anschließend, ob der letzte Zustand in F liegt.` : `Deine Antwort auf das Präfix stimmt nicht mit der Übergangstabelle überein. Prüfe das Lesen der Übergänge: Start 0, erstes Zeichen ${word[0]} → ${path[1]}; danach ${word[1]} → ${path[2]}. Eine Schwierigkeit bei diesem Teillauf ist damit beobachtet.`}<p>Ändere oben deine Antwort und prüfe erneut.</p></div>}
    </div>
    {independent && !help && result !== "correct" && <button onClick={() => setHelp(true)}>Ich brauche Hilfe</button>}
    {support && result !== "correct" && <div className="wl-help"><h3>Hilfe in deinem Tempo</h3><div className="wl-actions"><button onClick={() => setLevel(Math.max(level, 1))}>1 · Hinweis</button><button onClick={() => setLevel(Math.max(level, 2))}>2 · Teillauf</button><button onClick={() => setLevel(3)}>3 · Ganze Erklärung</button></div>
      {level >= 1 && <p>Verbrauche je Übergang genau ein Zeichen. Entscheide erst nach dem letzten Zeichen über die Akzeptanz.</p>}
      {level >= 2 && <p>Erste zwei Schritte: 0 —{word[0]}→ {path[1]} —{word[1]}→ {path[2]}. Noch ungelesen: {word.slice(2)}.</p>}
      {level >= 3 && <p>Vollständiger Lauf: {path.map((q,i) => i === 0 ? q : ` —${word[i-1]}→ ${q}`).join("")}. Die Eingabe ist jetzt leer. Nur Zustand 1 akzeptiert; dieses Wort wird {path[path.length-1] === 1 ? "akzeptiert" : "verworfen"}.</p>}
      {(level > 0 || diagnosis) && <><h3>Vorschlag für deinen Cheat Sheet</h3><p>Wortlauf im DEA · Gilt für deterministische endliche Automaten: Im Startzustand beginnen; je Zeichen den Übergang aus dem aktuellen Zustand lesen; am Wortende Zugehörigkeit zu F prüfen. Ein früher Besuch in F genügt nicht. Beispiel: 0 —b→ 1 —b→ 2, also bb verworfen.</p><label>Dein Eintrag – anpassen und auf Papier oder in deine Notiz-App übertragen<textarea defaultValue="DEA-Wortlauf: Start → ein Übergang pro Zeichen → erst am Ende F prüfen. Bei bb: 0 → 1 → 2, verworfen."/></label><button onClick={() => setCopied(true)}>Auf meinen Zettel übernommen</button>{copied && <p>Übernahme bestätigt. Lege den Zettel vor dem Transfer weg.</p>}</>}
    </div>}
  </>;
}

export default function WortlaufTrainer() {
  const [page, setPage] = useState(0);
  const [entry, setEntry] = useState(["", "", ""]);
  const [entryChecked, setEntryChecked] = useState(false);
  const [quiz, setQuiz] = useState(["", ""]);
  const [quizChecked, setQuizChecked] = useState(false);
  const [frame, setFrame] = useState(0);
  const [practice, setPractice] = useState(0);
  const [transfer, setTransfer] = useState(0);
  const [records, setRecords] = useState([]);
  const [ownWord, setOwnWord] = useState("");
  const [ownFeedback, setOwnFeedback] = useState("");
  const [reflection, setReflection] = useState("");
  const [demo, setDemo] = useState(false);
  const [session, setSession] = useState(0);
  const example = "aba";
  function changeAnswer(setter, values, i, value) { setter(values.map((v,j) => i === j ? value : v)); }
  function record(item) { setRecords(r => [...r, item]); }
  function resetDemo() { setDemo(true); setPage(2); setFrame(0); setPractice(0); setTransfer(0); setRecords([]); setSession(s => s+1); }
  return <div className="wl"><div className="wl-shell">
    <header><div className="wl-top"><span className="wl-eyebrow">FORMALE SPRACHEN & AUTOMATEN / EINHEIT 01</span><button onClick={() => setDemo(!demo)}>{demo ? "Aufnahmehinweise ausblenden" : "Aufnahme vorbereiten"}</button></div><h1>Ein Wort. Ein Weg.<br/><span>Jeden Schritt verstehen.</span></h1><p className="wl-lead">Vom ersten Zeichen zur begründeten Entscheidung: lesen, selbst lösen, gezielt Hilfe nutzen – und anschließend ohne Zettel anwenden.</p><div className="wl-meta"><span>01 / DEA-Wortlauf</span><span>In deinem Tempo</span><span>Belegt am Vorlesungsskript</span></div></header>
    {demo && <aside className="wl-demo"><strong>Aufnahmeplan · 42 Sekunden</strong><p>0–7 Erklärung + Wortlauf · 7–13 Quiz · 13–23 eigene Antwort + Diagnose · 23–32 Hinweis + neuer Versuch · 32–42 Transfer ohne Zettel. Schnitte zwischen vorbereiteten Ansichten; keine beschleunigte Lernpflicht.</p><p>Für die Aufnahme verwendete Antworten sind inszenierte Beispiele, keine Diagnose deines Vorwissens.</p><button onClick={resetDemo}>Aufnahmestart zurücksetzen</button></aside>}
    <nav aria-label="Lernschritte">{steps.map((name,i) => <button key={name} aria-current={page === i ? "step" : undefined} onClick={() => setPage(i)}><span>{String(i+1).padStart(2,"0")}</span>{name}</button>)}</nav>
    <main>
      <section hidden={page !== 0}><div className="wl-eyebrow">DEINE UNTERLAGEN</div><h2>Der Stoff hat eine Reihenfolge.</h2><p>Fünf PDFs, 600 Seiten. Diese erste Einheit behandelt Grundlagen und deterministische Wortläufe. Alle weiteren Themen sind als noch nicht aufbereitet gekennzeichnet.</p>
        <div className="wl-roadmap">{[["Jetzt verfügbar", "Alphabet → Wort → Sprache → DEA-Wortlauf", "Hauptskript S. 26–33 und 66–78"], ["Noch offen", "Reguläre Ausdrücke, NEA, Umwandlungen, Minimierung", "Hauptskript S. 44–145"], ["Noch offen", "Pumping-Lemma und Abschlusseigenschaften", "Hauptskript S. 146–181"], ["Noch offen", "Grammatiken, Normalformen, Kellerautomaten und CYK", "Hauptskript S. 182–276; Ergänzungen"], ["Noch offen", "Turingmaschinen → Entscheidbarkeit → Berechenbarkeit → Komplexität", "Hauptskript S. 277–480"]].map(([status,title,ref]) => <article key={title}><small>{status}</small><h3>{title}</h3><p>{ref}</p></article>)}</div>
        <details><summary>Alle Dateien und Quellenhinweise</summary><p>Quellenordner: <code>{ROOT}</code>. PDF-Seiten ab 1; keine Quelldateien in die Galerie kopiert.</p><ul><li>{SOURCE} · 480 S. · Gesamtgliederung S. 6.</li><li>Reguläre Sprachen - Anmerkungen, Übungsaufgaben und Lösungen.pdf · 48 S. · DEA S. 7–14, NEA S. 15–22, Umwandlungen S. 23–30, Pumping-Lemma S. 34–47.</li><li>Kontextfreie Sprachen - Anmerkungen, Übungsaufgaben und Lösungen.pdf · 47 S. · Normalformen S. 4–13, CYK S. 14–30, Kellerautomaten S. 31–47.</li><li>CYK-Algorithmus.pdf · 13 S. · Verfahren S. 1–6, Beweis S. 7, Beispiel/Umsetzung S. 8–13. Überschneidet sich mit der vorigen Datei.</li><li>Beweis der Äquivalenz von Kontextfreien Grammatiken und Kellerautomaten.pdf · 12 S. · Beweise S. 1–6 und 8–12; S. 7 ergänzt eine fehlende Regel der Konstruktion.</li></ul><p>Offen: Das Hauptskript heißt „old“ und nennt DHBW Stuttgart. Die Übereinstimmung mit dem aktuellen Mosbacher Prüfungsumfang ist nicht bestätigt. Die Übersicht ist keine fachliche Vollprüfung aller Seiten.</p></details><button className="wl-primary" onClick={() => setPage(1)}>Mit meinem Vorwissen starten →</button></section>
      <section hidden={page !== 1}><div className="wl-eyebrow">ANKOMMEN · KEINE BENOTUNG</div><h2>Wo steigst du ein?</h2><p>Du möchtest bei Alphabet, Wort und Zustand beginnen. Im Chat hast du den Zustand A und die Ablehnung von 101 richtig bestimmt; die Länge von ε war noch unbekannt. ε enthält null Zeichen. Diese Beobachtungen gelten nur für die Einstiegsaufgabe. Die folgenden Fragen kannst du zur Wiederholung nutzen.</p>{[ ["Bei Σ = {a,b}: Was ist ab?", ["Ein Zeichen", "Ein Wort", "Weiß ich nicht"]], ["Wie viele Zeichen enthält ε?", ["0", "1", "Weiß ich nicht"]], ["Start q0; a wechselt q0 → q1 und q1 → q0. Zustand nach aa?", ["q0", "q1", "Weiß ich nicht"]] ].map(([question,options],i) => <label className="wl-question" key={question}>{question}<select value={entry[i]} onChange={e => {changeAnswer(setEntry,entry,i,e.target.value); setEntryChecked(false);}}><option value="">Bitte wählen</option>{options.map(o => <option key={o}>{o}</option>)}</select></label>)}<button className="wl-primary" disabled={entry.some(v => !v)} onClick={() => setEntryChecked(true)}>Einstieg auswerten</button>{entryChecked && <div className="wl-feedback" role="status">{entry.every((v,i) => v === ["Ein Wort","0","q0"][i]) ? "Alle drei Einstiegsantworten stimmen. Du kannst direkt zum Wortlauf gehen; die Grundlagen bleiben zugänglich." : "Einige Grundlagen sind noch offen oder wurden anders beantwortet. Lies die Grundlagen und verfolge das Beispiel Schritt für Schritt."}<p>ab ist ein Wort aus zwei Zeichen; ε hat Länge 0; q0 → q1 → q0 ergibt q0. Das beschreibt nur diese drei Antworten.</p><Cite pages="26–29, 66–72"/></div>}<label className="wl-question">Mein Lernziel / bisherige Schwierigkeiten<textarea placeholder="Zum Beispiel: Ich verliere beim Ablesen den aktuellen Zustand."/></label><button onClick={() => setPage(2)}>Zur Erklärung →</button><hr/><h3>Du warst schon hier?</h3><p>Hier wird kein Lernstand dauerhaft gespeichert. Notiere deinen bisherigen Stand und die zuletzt benötigte Hilfe für dich; beginne dann mit einer neuen Aufgabe ohne Cheat Sheet.</p><label>Mein vorheriger Stand<textarea placeholder="Letzte Aufgabe, benutzte Hilfe, offene Schwierigkeit"/></label><button onClick={() => {setTransfer(t => t+1); setPage(5);}}>Wiedereinstieg ohne Zettel →</button></section>
      <section hidden={page !== 2}><div className="wl-eyebrow">VERSTEHEN · DER AKTUELLE ZUSTAND IST DAS GEDÄCHTNIS</div><h2>Ein Zeichen lesen. Einen Übergang gehen.</h2><p>Ein deterministischer endlicher Automat (DEA) beginnt im Startzustand und liest das Wort von links nach rechts. Für jeden Zustand und jedes Zeichen gibt es genau einen Übergang. Er akzeptiert nur, wenn nach der gesamten Eingabe der aktuelle Zustand zu F gehört.</p><Cite pages="66, 68, 70, 72"/>
        <h3>Vom Alphabet zum Zustand</h3><p><b>Alphabet:</b> die erlaubten Zeichen, hier a und b. <b>Wort:</b> eine endliche Folge daraus, zum Beispiel aba mit Länge 3. <b>ε (Epsilon):</b> das Wort ohne Zeichen, mit Länge 0. ε ist kein zusätzliches Eingabezeichen. Eine <b>Sprache</b> ist eine Menge von Wörtern, etwa alle Wörter mit genau einem b.</p><Cite pages="26, 28–29, 33, 71"/><p><b>Zustand:</b> die aktuelle Situation des Automaten, im Diagramm ein Kreis. Der Startpfeil zeigt, wo du beginnst. Ein mit a oder b beschrifteter Pfeil sagt, wohin du beim Lesen dieses Zeichens gehst. Eine Schleife bleibt im selben Zustand; ein Doppelkreis kennzeichnet einen akzeptierenden Zustand. Erst wenn kein Zeichen mehr übrig ist, entscheidet dieser Zustand über die Annahme des Wortes. Bei ε bleibt der Automat direkt im Startzustand.</p><Cite pages="66–70, 72"/><p>Dein Ziel: jedes Zeichen genau einmal verarbeiten, den aktuellen Zustand festhalten und die Entscheidung am Wortende begründen.</p><details><summary>Grundlagen & Symbole – jederzeit nachlesen</summary><p>Σ (Sigma) ist ein endliches, nicht leeres Alphabet, hier {"{a,b}"}. Ein Wort ist eine endliche Zeichenfolge: ab ≠ ba. ε bezeichnet das leere Wort, |ε| = 0. Σ* enthält alle endlichen Wörter über Σ, einschließlich ε. Eine Sprache L ⊆ Σ* ist eine Menge solcher Wörter. Ein Präfix ist ein Anfangsstück, etwa ab von abab (Begriff hier für die Übung eingeführt).</p><Cite pages="26, 28–33"/><p>A = (Q, Σ, δ, q₀, F): Q sind die Zustände, δ ist die Übergangsfunktion, q₀ der Start, F die Menge akzeptierender Zustände. δ(q,c) verarbeitet ein Zeichen. δ*(q,w) verarbeitet ein ganzes Wort: δ*(q,ε) = q und δ*(q,wc) = δ(δ*(q,w),c). Eine Konfiguration (q,w) besteht aus aktuellem Zustand und ungelesenem Rest.</p><Cite pages="68, 70, 72"/></details>
        <div className="wl-example"><div className="wl-top"><h3>Durchgearbeitetes Beispiel · aba</h3><span className="wl-chip">{frame} / 3 Zeichen</span></div><Diagram current={run(example)[frame]}/><div className="wl-run"><span>Gelesen <b>{example.slice(0,frame) || "ε"}</b></span><span>Rest <b>{example.slice(frame) || "ε"}</b></span><span>Zustand <b>{run(example)[frame]}</b></span></div><p className="wl-feedback" aria-live="polite">{["Start in 0. Noch kein Zeichen gelesen.", "a gelesen: δ(0,a) = 0. Noch ba übrig.", "b gelesen: δ(0,b) = 1. Noch a übrig – noch nicht fertig!", "a gelesen: δ(1,a) = 1. Rest ε und 1 ∈ F: akzeptiert."][frame]}</p><div className="wl-actions"><button disabled={frame === 0} onClick={() => setFrame(f => f-1)}>Zurück</button><button className="wl-primary" disabled={frame === 3} onClick={() => setFrame(f => f+1)}>Nächstes Zeichen</button><button onClick={() => setFrame(0)}>Lauf zurücksetzen</button></div></div>
        <p>Der Automat aus dem Skript merkt sich, ob bisher kein b (0), genau ein b (1) oder mindestens zwei b (2) gelesen wurden. In 2 bleibt er für immer: Fang- bzw. Mülleimerzustand. Seine Sprache besteht genau aus den Wörtern mit einem b; beliebig viele a dürfen davor und danach stehen. ε wird verworfen, weil der Startzustand 0 nicht in F liegt.</p><Cite pages="67–71"/><p>Eigenes Anwendungsbeispiel: Eine Ereignisfolge soll genau eine Freigabe b enthalten; a steht für ein neutrales Ereignis. Der Automat prüft die Folge. Er führt selbst keine reale Freigabe aus. Automaten werden auch beim Erkennen von Wörtern in Compilern verwendet (Skript S. 22, 24).</p><button className="wl-primary" onClick={() => setPage(3)}>Gelesen – jetzt das Quiz →</button></section>
      <section hidden={page !== 3}><div className="wl-eyebrow">ABRUFEN · OHNE NACHLESEN VERSUCHEN</div><h2>Was entscheidet über Akzeptanz?</h2>{[["Wann akzeptiert ein DEA?", ["Sobald er einmal einen Endzustand besucht", "Wenn nach dem ganzen Wort der Zustand in F liegt"]], ["Was bewirkt das leere Wort ε beim Wortlauf?", ["Der Zustand bleibt unverändert", "Es wird ein zusätzlicher Übergang ausgeführt"]]].map(([question, options],i) => <label className="wl-question" key={question}>{question}<select value={quiz[i]} onChange={e => {changeAnswer(setQuiz,quiz,i,e.target.value);setQuizChecked(false);}}><option value="">Bitte wählen</option>{options.map(o => <option key={o}>{o}</option>)}</select></label>)}<button className="wl-primary" disabled={quiz.some(v => !v)} onClick={() => setQuizChecked(true)}>Quiz prüfen</button>{quizChecked && <div className="wl-feedback" role="status">{quiz[0] === "Wenn nach dem ganzen Wort der Zustand in F liegt" && quiz[1] === "Der Zustand bleibt unverändert" ? "Beide Antworten stimmen. Jetzt wendest du die Regeln selbst an." : "Prüfe zwei Punkte: Ist noch Eingabe übrig? Dann ist die Akzeptanz noch nicht entschieden. Bei ε wird kein Zeichen gelesen, also kein Übergang ausgeführt. Ändere deine Antworten für einen neuen Versuch."}<Cite pages="70, 72"/></div>}<button onClick={() => setPage(4)}>Selbst anwenden →</button></section>
      <section hidden={page !== 4}><Exercise key={`practice-${session}-${practice}`} word={practice % 2 === 0 ? "abab" : "baab"} onRecord={record} onNext={() => practice === 0 ? setPractice(1) : setPage(5)}/><hr/><h3>Leite selbst ein Beispiel her</h3><p>Erfinde ein anderes akzeptiertes Wort mit mindestens drei Zeichen. Erkläre dir anschließend, warum dein Wort akzeptiert wird.</p><label>Mein Wort<input value={ownWord} onChange={e => {setOwnWord(e.target.value);setOwnFeedback("");}} placeholder="Nur a und b"/></label><button onClick={() => setOwnFeedback(!/^[ab]{3,}$/.test(ownWord) ? "Verwende mindestens drei Zeichen aus {a,b}." : ownWord === "aba" ? "aba war das Beispiel. Finde ein anderes Wort." : run(ownWord).at(-1) === 1 ? "Dein Wort wird akzeptiert: genau ein b. Erkläre jetzt den Zusammenhang mit Zustand 1." : "Dieses Wort endet nicht in Zustand 1. Prüfe die Anzahl der b und versuche es erneut.")}>Eigenes Wort prüfen</button><p role="status">{ownFeedback}</p><label>Meine Erklärung oder ein eigener Anwendungsfall<textarea value={reflection} onChange={e => setReflection(e.target.value)} placeholder="Wofür könnten a und b stehen? Was müsste genau einmal vorkommen?"/></label><p className="wl-muted">Freie Erklärung zur Selbstreflexion; keine automatische KI-Bewertung. Vergleiche: 0 = kein b, 1 = genau ein b, 2 = mindestens zwei b.</p></section>
      <section hidden={page !== 5}><Exercise key={`transfer-${session}-${transfer}`} word={["aaba", "baba", "aaab", "abba"][transfer % 4]} independent onRecord={record} onNext={() => setPage(6)}/></section>
      <section hidden={page !== 6}><div className="wl-eyebrow">BEOBACHTEN · NICHT ÜBERINTERPRETIEREN</div><h2>Was hast du heute selbst gelöst?</h2>{records.length ? <ul className="wl-records">{records.map((r,i) => <li key={i}><b>{r.word}</b><span>korrekt · {r.attempts} Versuch(e) · {r.help ? "mit Unterstützung" : "ohne aufgerufene Hilfe"}{r.independent ? " · Transfer" : ""}</span></li>)}</ul> : <p>Noch keine korrekt geprüfte Wortaufgabe in dieser Sitzung.</p>}<p>Diese Beobachtungen gelten für die bearbeiteten Aufgaben. Sie belegen kein umfassendes Verständnis. Ein versteckter oder gelesener externer Zettel kann hier nicht erkannt werden.</p><label>Was brauche ich beim nächsten Mal?<textarea placeholder="Notiere konkrete Schwierigkeit, hilfreichen Hinweis und nächste Übung."/></label><p>Der Stand bleibt nur während dieses geöffneten Trainers erhalten. Übertrage ihn vor dem Schließen in deine Notizen. Beim Wiedereinstieg zuerst ohne Cheat Sheet lösen.</p><button className="wl-primary" onClick={() => {setTransfer(t => t+1);setPage(5);}}>Eine weitere Aufgabe ohne Zettel →</button></section>
    </main><footer><span>Gedanke dazwischen? Kurz auf Papier notieren, dann zur Aufgabe zurück.</span><span>Quellen: PDF-Seiten ab 1 · Beispiele ausdrücklich gekennzeichnet</span></footer>
  </div></div>;
}
