import React from "react";

export default function LegalPage({ privacy }) {
  return <article className="page legal-page"><a href="/">← Lerntrainer</a><h1>{privacy ? "Datenschutzerklärung" : "Impressum"}</h1>
    <h2>{privacy ? "Verantwortlicher" : "Betreiber"}</h2><p>Steven Braun<br />Goethestr. 38<br />32469 Petershagen<br />Deutschland<br /><a href="mailto:steven7braun@gmail.com">steven7braun@gmail.com</a></p>
    {!privacy ? <p>Der Lerntrainer wird privat betrieben. Er ist kein offizielles Angebot der DHBW.</p> : <>
      <p>Stand: 3. Oktober 2026</p>
      <h2>Gastnutzung und Browserspeicher</h2><p>Du kannst öffentliche Trainer ohne Konto nutzen. Lernstände, Ergebnisse, Notizen und Einstellungen werden dann ausschließlich im localStorage dieses Browsers gespeichert. Sie werden nicht an die Lernstand-Datenbank übertragen. Browserdaten können über die Kontoseite oder die Browser-Einstellungen gelöscht werden. Beim Löschen gehen lokale Lernstände verloren.</p>
      <h2>Benutzerkonto und Lernstände</h2><p>Bei Registrierung verarbeiten wir E-Mail-Adresse, Benutzer-ID, einen von Supabase verwalteten Passwort-Hash und Zeitstempel. Optional werden Anzeigename und die selbst gewählte Kurszugehörigkeit T-INF 25 gespeichert. Im Konto speichern wir deine Lernstände, Antworten, Quiz-Ergebnisse, Notizen, Prüfungsvorbereitungen und Einstellungen zur Wiederaufnahme und Synchronisierung. Andere Nutzer haben keinen Zugriff auf diese Daten. Es gibt keine öffentliche Rangliste.</p>
      <p>Rechtsgrundlage für die Bereitstellung des freiwillig angelegten Kontos und seiner Lernfunktionen ist Art. 6 Abs. 1 lit. b DSGVO. Die Angaben sind für die Gastnutzung nicht erforderlich. Ohne E-Mail-Adresse und Bestätigung kann kein Konto eingerichtet werden. Die Kursauswahl blendet gemeinsame Prüfungstermine ein und kann in den Einstellungen geändert werden.</p>
      <h2>Synchronisierung und Übernahme</h2><p>Gastdaten werden nur auf deine ausdrückliche Auswahl in dein Konto übernommen. Angemeldete Nutzer speichern ihren Kontostand zusätzlich getrennt im Browser, damit bei Verbindungsausfall weitergelernt werden kann. Ausstehende Änderungen werden nach Wiederverbindung synchronisiert. Bei konkurrierenden Änderungen entscheidest du, welchen Stand du verwenden möchtest. Beim Abmelden bleibt der getrennte Kontospeicher auf diesem Gerät für eine spätere Anmeldung erhalten. Auf gemeinsam genutzten Geräten solltest du nach der Nutzung die Browserdaten löschen.</p>
      <h2>Dienstleister und Hosting</h2><p>Supabase Pte. Ltd. stellt Authentifizierung, PostgreSQL-Datenbank und Backend-Funktionen bereit. Die primäre Projektdatenbank befindet sich in Frankfurt (eu-central-1). Hosting und Auslieferung der veröffentlichten Web-App erfolgen über Vercel Inc. Beim Aufruf können die Dienstleister technische Verbindungsdaten wie IP-Adresse, Zeitpunkt, angeforderte Ressource und Browserinformationen zur Bereitstellung und Sicherheit verarbeiten. Rechtsgrundlage dafür ist Art. 6 Abs. 1 lit. f DSGVO; unser Interesse ist ein funktionsfähiger und sicherer Dienst.</p>
      <p>Eine EU-Datenbankregion schließt Drittlandzugriffe durch internationale Dienstleister nicht vollständig aus. Informationen zu Auftragsverarbeitung, Unterauftragnehmern und vertraglichen Schutzmaßnahmen findest du im <a href="https://supabase.com/legal/customer-resources/data-processing-addendum">Supabase-DPA</a> und im <a href="https://vercel.com/legal/dpa">Vercel-DPA</a>. Weitere Informationen enthalten die Datenschutzhinweise von <a href="https://supabase.com/privacy">Supabase</a> und <a href="https://vercel.com/legal/privacy-notice">Vercel</a>.</p>
      <h2>E-Mail-Versand</h2><p>Bestätigungs- und Passwort-Reset-Mails werden über ein Mail-Basic-Postfach der IONOS SE versendet. Dazu werden Empfängeradresse, Nachrichteninhalt einschließlich des jeweiligen Bestätigungslinks und technisch notwendige Versanddaten verarbeitet. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO für die Bereitstellung des Kontos. Hinweise des Dienstleisters findest du in der <a href="https://www.ionos.de/terms-gtc/datenschutzerklaerung/">IONOS-Datenschutzerklärung</a>. Für Anliegen an den Betreiber gilt weiterhin die oben genannte Kontaktadresse.</p>
      <h2>Speicherdauer und Löschung</h2><p>Kontodaten werden für die Dauer des Kontos gespeichert. Die Account-Löschung entfernt das Auth-Konto und die zugeordneten aktiven Datensätze. Dienstleister können Daten in technischen Sicherungen und Sicherheitsprotokollen bis zum Ablauf ihrer jeweiligen Aufbewahrungsfristen vorhalten. Gastdaten und lokale Kontokopien bleiben bis zum Löschen im jeweiligen Browser erhalten. Die Löschung des Kontos entfernt dessen lokale Kopie in diesem Browser; auf weiteren Geräten müssen Browserdaten ebenfalls gelöscht werden.</p>
      <h2>Deine Rechte</h2><p>Du hast nach den gesetzlichen Voraussetzungen Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung und Datenübertragbarkeit sowie Widerspruch gegen Verarbeitungen auf Grundlage berechtigter Interessen. Kontodaten lassen sich als JSON exportieren und das Konto kann selbst gelöscht werden. Weitere Anliegen kannst du an die oben angegebene E-Mail-Adresse richten. Du kannst dich bei einer Datenschutzaufsichtsbehörde beschweren, insbesondere der <a href="https://www.ldi.nrw.de/">Landesbeauftragten für Datenschutz und Informationsfreiheit Nordrhein-Westfalen</a>.</p>
      <h2>Tracking und automatisierte Entscheidungen</h2><p>Die Anwendung enthält keine Marketing-Tracker oder Analyse-Pixel. localStorage dient Lernfunktionen und der Verwaltung der Anmeldung. Es erfolgen keine automatisierten Entscheidungen mit rechtlicher oder vergleichbar erheblicher Wirkung.</p>
    </>}
  </article>;
}
