const exams = [
  { id: "fsa", title: "Formale Sprachen", date: "2026-11-16", weeklyMinutes: 75, priority: 4 },
  { id: "netz", title: "Netztechnik", date: "2026-11-19", weeklyMinutes: 90, priority: 2 },
  { id: "mathe", title: "Angewandte Mathematik", date: "2026-11-23", weeklyMinutes: 105, priority: 1 },
  { id: "systemnah", title: "Systemnahe Programmierung", date: "2026-11-26", weeklyMinutes: 90, priority: 3 },
  { id: "web", title: "Web Engineering 2", date: null, weeklyMinutes: 60, priority: 5 },
];

const targets = [
  {
    id: "diagnose-mathe",
    examId: "mathe",
    trainerSlug: "diagnose-mathe-3",
    kind: "diagnostic",
    relevance: "B",
    availableFrom: "2026-09-28",
    minutes: 25,
    source: "Mathe_Sem3_Heine_Skript_1_Differentialrechnung-mehrdimensional.pdf und Übung1_Differentialrechnung.pdf",
    reason: "Der kalte Einstiegstest bestimmt, ob Grundlagenaufbau, Lückenschließung oder Transfer zuerst kommt.",
  },
  {
    id: "diagnose-netz",
    examId: "netz",
    trainerSlug: "diagnose-netztechnik",
    kind: "diagnostic",
    relevance: "B",
    availableFrom: "2026-09-29",
    minutes: 25,
    source: "KuN 01–03: IT-Infrastruktur, OSI-Modell und Computernetzwerke/Internet",
    reason: "Der Test prüft ausschließlich den aktuell vorhandenen Kursstoff und setzt danach die passende Intensität.",
  },
  {
    id: "diagnose-systemnah",
    examId: "systemnah",
    trainerSlug: "diagnose-systemnahe-programmierung",
    kind: "diagnostic",
    relevance: "B",
    availableFrom: "2026-09-30",
    minutes: 25,
    source: "Systemnahe Programmierung 01–03: Einführung, Programmiermodell und Programmiersprachen",
    reason: "Der Test trennt fehlende Hardwaregrundlagen von Lücken bei Architektur und Übersetzung.",
  },
  {
    id: "diagnose-fsa",
    examId: "fsa",
    trainerSlug: "diagnose-formale-sprachen",
    kind: "diagnostic",
    relevance: "B",
    availableFrom: "2026-10-01",
    minutes: 25,
    source: "Reguläre Sprachen sowie Kontextfreie Sprachen – Anmerkungen, Übungsaufgaben und Lösungen",
    reason: "Der Test prüft aktuelle Grundlagen, ohne den Umfang aus dem alten Stuttgarter Hauptskript abzuleiten.",
  },
  ...[
    ["1.1", "Felder, Definitionsbereiche und Niveaumengen", "mathe-funktionen", "Zuerst Funktionen mehrerer Variablen und ihre Definitionsbereiche verstehen."],
    ["2.1", "Partielle und normierte Richtungsableitungen", "mathe-funktionen", "Auf dem Funktionsbegriff aufbauend Änderungen in einzelnen Richtungen berechnen."],
    ["2.2", "Steilster Anstieg und Tangenten", "mathe-funktionen", "Gradient und Richtungsableitung geometrisch als Anstieg und Tangente deuten."],
    ["3.1", "Totale Differenzierbarkeit und Tangentialebene", "mathe-funktionen", "Partielle Ableitungen zur linearen Näherung einer Funktion zusammenführen."],
    ["3.3", "Mehrdimensionale Kettenregel", "mathe-funktionen", "Ableitungen und lineare Näherungen auf verkettete Funktionen übertragen."],
    ["3.fehler", "Fehlerfortpflanzung", "mathe-funktionen", "Lineare Näherung und Ableitungen auf Unsicherheiten der Eingabewerte anwenden."],
    ["5.1", "Stationäre Punkte und Hesse-Test", "mathe-autodiff", "Nach den Ableitungsregeln stationäre Punkte finden und mit zweiten Ableitungen prüfen."],
    ["9.1", "Lagrange und Kandidatenvergleich", "mathe-regression", "Die Suche nach Extremwerten auf Aufgaben mit Nebenbedingungen erweitern."],
  ].map(([topicId, title, trainerSlug, orderReason], index) => ({
    id: `mathe-${topicId}`, topicId, title, examId: "mathe", trainerSlug, order: index + 1, orderReason,
    kind: "focus", relevance: "B", availableFrom: "2026-09-28", minutes: 25,
    source: "Mathe_Sem3_Heine_Skript_1_Differentialrechnung-mehrdimensional.pdf und Übung1_Differentialrechnung.pdf",
    reason: "Dieses Thema ist durch die aktuellen Heine-Unterlagen zur Differentialrechnung belegt.",
  })),
  ...[
    ["netz-infrastruktur", "IT-Infrastruktur und Netzformen", "Zuerst Netzformen, Rollen und Infrastruktur einordnen."],
    ["netz-osi", "Kommunikation in Schichten denken", "Auf den Netzrollen aufbauend die Aufgaben der Kommunikationsschichten unterscheiden."],
    ["netz-internet", "Paketvermittlung, Verzögerung und Durchsatz", "Das Schichtenmodell auf Paketwege, Verzögerungen und Engpässe anwenden."],
  ].map(([id, title, orderReason], index) => ({
    id, title, order: index + 1, orderReason, examId: "netz", trainerSlug: "netztechnik-lernreise",
    kind: "focus", relevance: "B", availableFrom: "2026-09-29", minutes: 25,
    source: "KuN 01–03: IT-Infrastruktur, OSI-Modell und Computernetzwerke/Internet",
    reason: "Diese Einheit entspricht dem aktuell vorhandenen Kursmaterial.",
  })),
  ...[
    ["systemnah-embedded", "Eingebettete Systeme und Zielhardware", "Zuerst Zielhardware und Speicherarten eines eingebetteten Systems kennenlernen."],
    ["systemnah-architektur", "Wie der Prozessor Programme ausführt", "Mit dem Hardwaremodell den Befehlszyklus und die Rechnerarchitektur verstehen."],
    ["systemnah-sprachen", "Von Maschinencode zu C und zurück", "Die Programmausführung mit Maschinencode, Assembler und Übersetzung verknüpfen."],
  ].map(([id, title, orderReason], index) => ({
    id, title, order: index + 1, orderReason, examId: "systemnah", trainerSlug: "systemnahe-programmierung-lernreise",
    kind: "focus", relevance: "B", availableFrom: "2026-09-30", minutes: 25,
    source: "Systemnahe Programmierung 01–03: Einführung, Programmiermodell und Programmiersprachen",
    reason: "Diese Einheit ist durch die aktuellen Folien belegt.",
  })),
  {
    order: 1, orderReason: "Zuerst den Weg vom Browser über den Server bis zur Antwort verstehen.",
    id: "web-request-response", title: "Vom Klick zur Antwort", examId: "web", trainerSlug: "web-fullstack-verstehen",
    kind: "focus", relevance: "B", availableFrom: "2026-10-01", minutes: 25,
    source: "web-basics-advanced.pdf, S. 4, 11–21; api.pdf, S. 14–15; database.pdf, S. 20–21",
    reason: "Browser, Server und HTTP sind als vollständige Einheit im aktuellen Fullstack-Trainer vorhanden.",
  },
  {
    id: "fsa-wortlauf",
    order: 2, orderReason: "Mit Alphabet, Wörtern und Sprachen vollständige Wortläufe im Automaten verfolgen.",
    title: "Deterministische Wortläufe",
    examId: "fsa",
    trainerSlug: "fsa-pruefungstraining",
    roundGoal: "dfa",
    kind: "focus",
    relevance: "B",
    availableFrom: "2026-10-01",
    minutes: 15,
    source: "Reguläre Sprachen – Anmerkungen, Übungsaufgaben und Lösungen, Abschnitt DEA",
    reason: "Deterministische Wortläufe sind im aktuellen Übungsmaterial belegt; weiterführender Altstoff bleibt ausgeschlossen.",
  },
  {
    order: 1, orderReason: "Zuerst Alphabet, Wort, leeres Wort und Sprache sicher unterscheiden.",
    id: "fsa-grundlagen", title: "Alphabet, Wörter und Sprachen", examId: "fsa", trainerSlug: "fsa-pruefungstraining", roundGoal: "basics",
    kind: "focus", relevance: "B", availableFrom: "2026-10-01", minutes: 15,
    source: "Aktuelle Unterlagen zu regulären Sprachen: Alphabet, Wörter, leeres Wort und Sprache",
    reason: "Grundbegriffe eigenständig anwenden, bevor vollständige DEA-Wortläufe geübt werden.",
  },
  {
    order: 3, orderReason: "Nach Wortläufen und Akzeptanz dieselben Wortmengen durch reguläre Ausdrücke beschreiben.",
    id: "fsa-regulaere-ausdruecke", title: "Reguläre Ausdrücke lesen und anwenden", examId: "fsa", trainerSlug: "fsa-pruefungstraining", roundGoal: "regex",
    kind: "focus", relevance: "B", availableFrom: "2026-10-01", minutes: 15,
    source: "Reguläre Sprachen - Anmerkungen, Übungsaufgaben und Lösungen.pdf, S. 1–6",
    reason: "Reguläre Ausdrücke ergänzen die Grundlagen und bereiten die belegten Umwandlungen in endliche Automaten vor.",
  },
];

export function getSemesterLearningProgram() {
  return {
    timezone: "Europe/Berlin",
    fixedWeeklyMinutes: 420,
    reserveWeeklyMinutes: 60,
    reserveDailyMinutes: 15,
    reviewDailyMinutes: 20,
    minimumMinutes: 10,
    dayMinutes: { 1: 90, 2: 90, 3: 90, 4: 90, 5: 60 },
    reviewIntervalsDays: [1, 3, 7],
    exams: exams.map((exam) => ({ ...exam })),
    targets: targets.map((target) => ({ ...target })),
  };
}
