const exams = [
  { id: "fsa", title: "Formale Sprachen", date: "2026-11-16", weeklyMinutes: 90, priority: 4 },
  { id: "netz", title: "Netztechnik", date: "2026-11-19", weeklyMinutes: 105, priority: 2 },
  { id: "mathe", title: "Mathematik 3", date: "2026-11-23", weeklyMinutes: 120, priority: 1 },
  { id: "systemnah", title: "Systemnahe Programmierung", date: "2026-11-26", weeklyMinutes: 105, priority: 3 },
];

const targets = [
  {
    id: "diagnose-mathe",
    examId: "mathe",
    trainerSlug: "diagnose-mathe-3",
    kind: "diagnostic",
    relevance: "B",
    availableFrom: "2026-09-28",
    minutes: 25,
    source: "Mathe_Sem3_Heine_Skript_1_Differentialrechnung-mehrdimensional.pdf und Übung1_Differentialrechnung.pdf",
    reason: "Der kalte Einstiegstest bestimmt, ob Grundlagenaufbau, Lückenschließung oder Transfer zuerst kommt.",
  },
  {
    id: "diagnose-netz",
    examId: "netz",
    trainerSlug: "diagnose-netztechnik",
    kind: "diagnostic",
    relevance: "B",
    availableFrom: "2026-09-29",
    minutes: 25,
    source: "KuN 01–03: IT-Infrastruktur, OSI-Modell und Computernetzwerke/Internet",
    reason: "Der Test prüft ausschließlich den aktuell vorhandenen Kursstoff und setzt danach die passende Intensität.",
  },
  {
    id: "diagnose-systemnah",
    examId: "systemnah",
    trainerSlug: "diagnose-systemnahe-programmierung",
    kind: "diagnostic",
    relevance: "B",
    availableFrom: "2026-09-30",
    minutes: 25,
    source: "Systemnahe Programmierung 01–03: Einführung, Programmiermodell und Programmiersprachen",
    reason: "Der Test trennt fehlende Hardwaregrundlagen von Lücken bei Architektur und Übersetzung.",
  },
  {
    id: "diagnose-fsa",
    examId: "fsa",
    trainerSlug: "diagnose-formale-sprachen",
    kind: "diagnostic",
    relevance: "B",
    availableFrom: "2026-10-01",
    minutes: 25,
    source: "Reguläre Sprachen sowie Kontextfreie Sprachen – Anmerkungen, Übungsaufgaben und Lösungen",
    reason: "Der Test prüft aktuelle Grundlagen, ohne den Umfang aus dem alten Stuttgarter Hauptskript abzuleiten.",
  },
  {
    id: "mathe-funktionen",
    examId: "mathe",
    trainerSlug: "mathe-funktionen",
    kind: "focus",
    relevance: "B",
    availableFrom: "2026-09-28",
    minutes: 70,
    source: "Mathe_Sem3_Heine_Skript_1_Differentialrechnung-mehrdimensional.pdf und Übung1_Differentialrechnung.pdf",
    reason: "Mehrdimensionale Ableitungen und ihre Anwendungen sind durch aktuelle Kursunterlagen belegt.",
  },
  {
    id: "netz-grundlagen",
    examId: "netz",
    trainerSlug: "netztechnik-lernreise",
    kind: "focus",
    relevance: "B",
    availableFrom: "2026-09-29",
    minutes: 65,
    source: "KuN 01–03: IT-Infrastruktur, OSI-Modell und Computernetzwerke/Internet",
    reason: "Die drei Einheiten entsprechen dem aktuell vorhandenen Kursmaterial.",
  },
  {
    id: "systemnah-grundlagen",
    examId: "systemnah",
    trainerSlug: "systemnahe-programmierung-lernreise",
    kind: "focus",
    relevance: "B",
    availableFrom: "2026-09-30",
    minutes: 65,
    source: "Systemnahe Programmierung 01–03: Einführung, Programmiermodell und Programmiersprachen",
    reason: "Embedded-Systeme, Rechnerarchitektur und Übersetzung sind durch aktuelle Folien belegt.",
  },
  {
    id: "fsa-dea",
    examId: "fsa",
    trainerSlug: "dea-wortlauf",
    kind: "focus",
    relevance: "B",
    availableFrom: "2026-10-01",
    minutes: 60,
    source: "Reguläre Sprachen – Anmerkungen, Übungsaufgaben und Lösungen, Abschnitt DEA",
    reason: "Deterministische Wortläufe sind im aktuellen Übungsmaterial belegt; weiterführender Altstoff bleibt ausgeschlossen.",
  },
];

export function getSemesterLearningProgram() {
  return {
    timezone: "Europe/Berlin",
    fixedWeeklyMinutes: 420,
    reserveWeeklyMinutes: 60,
    reviewDailyMinutes: 20,
    minimumMinutes: 10,
    dayMinutes: { 1: 90, 2: 90, 3: 90, 4: 90, 5: 60 },
    reviewIntervalsDays: [1, 3, 7],
    exams: exams.map((exam) => ({ ...exam })),
    targets: targets.map((target) => ({ ...target })),
  };
}
