import { field, source, task } from "./data.js";

// Five sections × (16 checked + 4 self-assessed points) = 100 points.
function section(id, title, chapters, family, prompt, answers, solution, rubric) {
  const pages = {1:[1,6],2:[7,12],3:[13,17],4:[18,25],5:[26,31],6:[32,40],7:[41,47],8:[48,53],9:[54,58]};
  return { ...task(prompt, answers.map(([label,answer,extra]) => field(label,answer,"", "Rechenschritt", {points:2,...extra})),solution),
    id, title, chapters, chapter:chapters[0], family, source:source(chapters[0],...pages[chapters[0]]),
    sources:chapters.map(chapter=>source(chapter,...pages[chapter])), own:true, prerequisites:chapters,
    rubric:rubric.map(text=>({text,points:2})), points:20 };
}

export const exams = [
  { id:"probe-a", title:"A · Temperaturfeld und quadratisches Modell", minutes:60, tasks:[
    section("a-feld","Feld und Messpfad",[1,2,3],"3.3",
      "f(x,y)=x²+xy, P=(1,2), u=(3,4), g(t)=(t,2t). Beschreibe Definitionsbereich und Feldtyp auf Papier. Berechne die Werte unten; T ist die Tangentialebene bei P, D die normierte Richtungsableitung. Leite f∘g bei t=1 ab und begründe die Jacobi-Reihenfolge.",
      [["Ausgabedimension",1],["f(P)",3],["fₓ(P)",4],["fᵧ(P)",1],["‖u‖",5],["D",3.2],["T(1,1;2)",3.4],["(f∘g)′(1)",6]],
      ["Skalarfeld auf ℝ²; ∇f=(2x+y,x), bei P=(4,1).", "D=(4·3+1·4)/5=16/5; T=3+4(x−1)+(y−2).", "J_f(g(1))=[4,1], J_g=(1,2)ᵀ; Produkt 6, Kontrolle f∘g=3t²."],
      ["1 P: Definitionsbereich ℝ² und Skalarfeld begründet; 1 P: stetige partielle Ableitungen als hinreichende Voraussetzung der Linearisierung genannt.","1 P: J_f(g(1))J_g(1) mit Dimensionen (1×2)(2×1); 1 P: Tangentialebene einschließlich Verschiebung auf Papier hergeleitet."]),
    section("a-graph","Verzweigter Graph und Krümmung",[4,5],"4.3",
      "v=x+y, L=v²+xy, x=1,y=2. Zeichne den Graphen und leite rückwärts ab. Bestimme H_L. Klassifiziere den stationären Ursprung. Begründe die Adjoint-Summe und den Hesse-Test.",
      [["v",3],["L",11],["v̄",6],["x̄",8],["ȳ",7],["H11",2],["H12",3],["Kleinster Eigenwert H",-1]],
      ["v=3,L=9+2=11. v̄=2v=6; x̄=6+y=8,ȳ=6+x=7.","L=x²+3xy+y²; H=[[2,3],[3,2]], Eigenwerte 5,−1. Ursprung stationär und Sattel."],
      ["1 P: Graph zeigt beide Pfade zu x und y; 1 P: lokale Ableitungen und deren Summierung korrekt dargestellt.","1 P: ∇L(0)=0 geprüft; 1 P: Sattel aus gemischten Eigenwertvorzeichen begründet."]),
    section("a-reg","Regression mit Bias",[6],"6.1",
      "Punkte (−1,1),(0,1),(1,4). Passe ŷ=β₀+β₁x an. Stelle X auf, leite die Normalengleichung aus dem quadratischen Fehler her und löse sie. Erfasse den Residuenquadratsummenwert RSS.",
      [["XtX11",3],["XtX12",0],["XtX22",2],["Xty1",6],["Xty2",3],["β₀",2],["β₁",1.5],["RSS",1.5]],
      ["X=[[1,−1],[1,0],[1,1]], XtX=diag(3,2), Xty=(6,3).", "β=(2,3/2), Vorhersagen (1/2,2,7/2), Residuen (1/2,−1,1/2), RSS=3/2."],
      ["1 P: X mit Bias korrekt; 1 P: ∇L=2XtXβ−2Xty=0 hergeleitet.","1 P: voller Spaltenrang begründet; 1 P: κ(XtX)=κ(X)² und Vorteil von QR erklärt."]),
    section("a-pca","Optimierung und Hauptachsen",[7,9],"9.2",
      "GD: f(x,y)=x²+2y², Start (1,1), η=1/4; zwei Schritte. PCA: Daten (2,0),(−2,0),(0,1),(0,−1). Berechne Σ nach 1/n, größten Eigenwert und erklärten Anteil. Leite das PCA-Eigenwertproblem mit Lagrange her und begründe η.",
      [["GD x₁",0.5],["GD y₁",0],["GD x₂",0.25],["GD y₂",0],["Σ11",2],["Σ22",0.5],["λmax",2],["Erklärter Anteil",0.8]],
      ["H_f=diag(2,4), 0<η<1/2. Schritte (1/2,0),(1/4,0).", "μ=0, Σ=diag(2,1/2). v₁=±(1,0), λ₁=2, Anteil 2/(2+1/2)=4/5.","L(v,λ)=vᵀΣv−λ(vᵀv−1); 2Σv−2λv=0. Auf der Einheitskugel größter Eigenwert = maximale Varianz."],
      ["1 P: offene Schranke η<2/4; 1 P: Gültigkeit auf das positiv definite quadratische Problem beschränkt.","1 P: Lagrange-Funktion mit Normbedingung; 1 P: Eigenwertgleichung und Auswahl des größten Eigenwerts begründet."]),
    section("a-integral","Dreiecksdichte und Kreisscheibe",[8],"8.dichte",
      "D={0≤y≤x≤2}, p=c auf D, sonst 0. Normiere p und berechne Momente. Beschreibe D in umgekehrter Reihenfolge. Unabhängig davon: Integriere x²+y² über die Einheitskreisscheibe in Polarkoordinaten.",
      [["c",0.5],["P(X≤1)",0.25],["E[X]",4/3],["E[Y]",2/3],["E[XY]",1],["Cov(X,Y)",1/9],["Polar: Potenz von r im Integranden",3],["Kreisintegral / π",0.5]],
      ["Fläche D=2; c=1/2. Horizontal: 0≤y≤2, y≤x≤2. p_X=x/2 und p_Y=(2−y)/2.","E[X]=4/3,E[Y]=2/3,E[XY]=1; Cov=1−8/9=1/9; P(X≤1)=1/4.","Polar: 2π∫₀¹r³dr=π/2."],
      ["1 P: Skizze mit Grenzen; 1 P: Reihenfolgewechsel 0≤y≤2, y≤x≤2 korrekt.","1 P: Randdichten mit ihrem Träger; 1 P: Polar-Jacobian als Betrag der Determinante hergeleitet."]),
  ]},
  { id:"probe-b", title:"B · Nichtlineare Schicht und QR", minutes:60, tasks:[
    section("b-feld","Nichtlineare Schicht",[1,2,3],"3.2",
      "g(x,y)=(x²+y,xy), f(u,v)=u−v², P=(1,1). Berechne Zwischenpunkt, J_g, h=f∘g und hₓ. Stelle die Tangentialebene von h auf Papier auf. Diskutiere die Niveaumenge h=h(P) lokal und die Dimensionen.",
      [["g₁(P)",2],["g₂(P)",1],["Jg11",2],["Jg12",1],["Jg21",1],["Jg22",1],["h(P)",1],["hₓ(P)",0]],
      ["g(P)=(2,1), Jg=[[2,1],[1,1]], Jf=[1,−2].", "Jh=[0,−1], h(P)=1; T=1−(y−1). Gradient (0,−1) ist normal zur lokalen Niveaulinie, die dort horizontale Tangente hat."],
      ["1 P: Dimensionen (1×2)(2×2); 1 P: äußere Ableitung am Zwischenpunkt (2,1) ausgewertet.","1 P: T=1−(y−1) hergeleitet; 1 P: Skalarfeld auf ℝ² und lokale Tangentenrichtung (1,0) begründet."]),
    section("b-graph","Sigmoidverlust und Taylor",[4,5],"4.2",
      "z=wx+b, a=σ(z), L=(a−1)²/2, x=2,w=1,b=−2. Berechne Werte und Adjoints. Separat: Taylor von exp(x−2y) bei 0; erfasse den xy-Koeffizienten. Erläutere die übrigen Taylor-Terme auf Papier.",
      [["z",0],["a",0.5],["L",0.125],["ā",-0.5],["z̄",-0.125],["w̄",-0.25],["b̄",-0.125],["Taylor xy-Koeffizient",-2]],
      ["z=0,a=1/2,L=1/8. ā=−1/2,z̄=−1/8,w̄=−1/4,b̄=−1/8.","T₂=1+x−2y+x²/2−2xy+2y²; H=[[1,−2],[−2,4]]."],
      ["1 P: lokale Sigmoid-Ableitung a(1−a); 1 P: alle Graphkanten einschließlich Parameterpfade richtig.","1 P: vollständiges Taylorpolynom; 1 P: erklärt, warum semidefinites H hier keinen Extremtest ohne stationären Punkt erlaubt."]),
    section("b-reg","QR statt Normalenmatrix",[6],"6.3",
      "Q hat Zeilen (1;0),(0;3/5),(0;4/5); R=[[2,1],[0,2]], y=(3,1,3). Prüfe QᵀQ, berechne d, löse Rβ=d und bestimme das Residuum r=y−QRβ. Erfasse RSS. Begründe das Verfahren.",
      [["QtQ11",1],["QtQ12",0],["d₁",3],["d₂",3],["β₁",0.75],["β₂",1.5],["r₂",-0.8],["RSS",1]],
      ["QᵀQ=I, d=(3,3). β₂=3/2, β₁=(3−3/2)/2=3/4.","QRβ=Qd=(3,9/5,12/5), r=(0,−4/5,3/5), RSS=1."],
      ["1 P: beide Spaltennormen und Skalarprodukt geprüft; 1 P: Rückwärtseinsetzen nachvollziehbar.","1 P: invertierbares R/voller Spaltenrang genannt; 1 P: Qᵀr=0 als Optimalitätskontrolle gezeigt."]),
    section("b-pca","Momentum und verschobene Daten",[7,9],"7.2",
      "Momentum für f=x²: x₀=1,v₀=0,η=1/4,γ=1/2. Berechne zwei Schritte. PCA der Punkte (1,2),(3,2),(5,2): Mittelwert, größte Varianz, Projektion des ersten Punktes auf v=(1,0). Leite die optimale Achse her.",
      [["v₁",0.5],["x₁",0.5],["v₂",0.5],["x₂",0],["μx",3],["μy",2],["λmax",8/3],["z₁",-2]],
      ["v₁=1/2,x₁=1/2; v₂=(1/2)(1/2)+(1/4)·1=1/2,x₂=0.","Zentrierte Daten (−2,0),(0,0),(2,0), Σ=diag(8/3,0). v=±(1,0), 100% Varianz; für festes v=(1,0) ist z₁=−2."],
      ["1 P: Momentum-Konvention korrekt; 1 P: erklärt, warum bei x₂=0 noch v₂≠0 ist und der nächste Schritt überschwingt.","1 P: Varianzmaximierung mit Normbedingung und Lagrange; 1 P: Zentrierung und 1/n-Konvention begründet."]),
    section("b-integral","Gekrümmtes Gebiet und nichtkonstante Dichte",[8],"8.2",
      "D liegt zwischen y=x² und y=2x für 0≤x≤2. Berechne Fläche und ∫∫_D x. Separat: p=cx auf [0,1]². Normiere, berechne E[X], E[Y], P(X≤1/2). Separat: Integriere 1 über den Kreisring 1≤r≤2.",
      [["Fläche D",4/3],["Integral x über D",4/3],["c",2],["E[X]",2/3],["E[Y]",0.5],["P(X≤1/2)",0.25],["Ringfläche / π",3],["Polar-Jacobian bei r=2",2]],
      ["Vertikal x²≤y≤2x; horizontal y/2≤x≤√y, 0≤y≤4. Fläche=4/3, Moment=4/3.","p=2x, p_X=2x,p_Y=1; E[X]=2/3,E[Y]=1/2,P=1/4.","Ringfläche=2π∫₁²rdr=3π."],
      ["1 P: beide Gebietsgrenzen skizziert; 1 P: horizontaler Ansatz mit √y korrekt.","1 P: Nichtnegativität, Träger und Normierung der Dichte; 1 P: r im polaren Flächenelement erklärt."]),
  ]},
  { id:"probe-c", title:"C · Filter, Mini-Batch und Nebenbedingung", minutes:60, tasks:[
    section("c-feld","Helligkeitsfeld und Sensorpfad",[1,2,3],"2.3",
      "I(x,y)=x²−y²+2x, P=(1,1). Berechne Wert, Gradient und Laplace. Der Sensor folgt g(t)=(t,t²); berechne (I∘g)′(1). Richtung u=(0,3): normierte Ableitung. T ist die Tangentialebene bei P. Beschreibe N_{−1} und den diskreten Laplace-Kern auf Papier.",
      [["I(P)",2],["Iₓ(P)",4],["Iᵧ(P)",-2],["Iₓₓ",2],["ΔI",0],["(I∘g)′(1)",0],["D normiert",-2],["T(1,1;1)",2.4]],
      ["∇I=(2x+2,−2y), H=diag(2,−2), ΔI=0.","J_I(P)=[4,−2], Jg(1)=(1,2)ᵀ, Ableitung 0. Richtung (0,1): −2; T=2+4(x−1)−2(y−1).", "I=−1 ⇔ (x+1)²−y²=0 ⇔ y=±(x+1). Diskreter Laplace-Kern [[0,1,0],[1,−4,1],[0,1,0]]."],
      ["1 P: N₋₁ als verschobenes Geradenkreuz; 1 P: erklärt, warum ΔI=0 keine ebene Fläche beweist.","1 P: diskreter Kern und h²-Skalierung; 1 P: Kettenregel mit passenden Auswertungsstellen."]),
    section("c-graph","Gemeinsam genutzter Zwischenknoten",[4,5],"4.3",
      "u=xy, v=u+x, L=uv, x=2,y=1. Berechne Knoten und Adjoints. Separat: q=x²+y²−z². Erfasse det H_q und begründe die Klassifikation des Ursprungs und die Grenzen des Hesse-Tests.",
      [["u",2],["v",4],["L",8],["v̄",2],["ū",6],["x̄",8],["ȳ",12],["det Hq",-8]],
      ["u=2,v=4,L=8. v̄=u=2,ū=v+v̄=6. x̄=ū·y+v̄=8,ȳ=ū·x=12.","Hq=diag(2,2,−2), det=−8; Ursprung stationär, Eigenwerte gemischt, daher Sattel."],
      ["1 P: direkter und indirekter Beitrag zu ū gezeigt; 1 P: zusätzlicher direkter x-Pfad über v berücksichtigt.","1 P: gemischte Eigenwertvorzeichen statt bloßer 3D-Determinantenregel; 1 P: semidefinite Hesse kann allein nicht klassifizieren."]),
    section("c-reg","Regression ohne Achsenabschnitt",[6],"6.2",
      "X=[[1,0],[0,1],[1,1]], y=(1,2,4). Modell ohne Bias. Berechne XtX, Xty, β und RSS. Leite Normalengleichung her und erläutere Unterschiede zum Modell mit Bias.",
      [["XtX11",2],["XtX12",1],["XtX22",2],["Xty1",5],["Xty2",6],["β₁",4/3],["β₂",7/3],["RSS",1/3]],
      ["XtX=[[2,1],[1,2]], Xty=(5,6), det=3. β=(4/3,7/3).", "Vorhersagen (4/3,7/3,11/3), Residuen (−1/3,−1/3,1/3), RSS=1/3."],
      ["1 P: Gradient des Fehlers hergeleitet; 1 P: vollen Spaltenrang anhand det(XtX)=3 begründet.","1 P: fehlende Eins-Spalte und Modellinterpretation erklärt; 1 P: QR als stabilere Alternative ohne explizite Inverse erklärt."]),
    section("c-pca","Mini-Batch und begrenzte Varianz",[7,9],"9.1",
      "Lᵢ=½(wxᵢ−yᵢ)², D=(1,2),(2,2),(3,4), w=1. Berechne Einzelgradienten, Full-Mittel und Update mit Batch {1,3}, η=0,1. Separat: Maximiere vᵀΣv mit Σ=diag(4,1), ‖v‖=1. Bestimme größte Varianz und Anteil. Außerdem: größtes Rechteck bei Umfang 12, Fläche?",
      [["g₁",-1],["g₂",0],["g₃",-3],["Full-Mittel",-4/3],["w neu",1.2],["Maximale Varianz",4],["Erklärter Anteil",0.8],["Rechteckfläche",9]],
      ["Einzelgradienten (−1,0,−3), Full=−4/3, Batch=−2, w neu=1,2.","Lagrange: Σv=λv. Achsen ±e₁,±e₂ mit Werten 4 und 1; Maximum 4, Anteil 4/5.","Rechteck 2x+2y=12: x=y=3, A=9, Randfläche 0."],
      ["1 P: Batchmittel statt Summe verwendet und Zufallscharakter erklärt; 1 P: Full- und Mini-Batch-Unterschied erläutert.","1 P: Lagrange mit Normbedingung und Kandidatenvergleich für PCA; 1 P: Rechteckoptimum durch Nebenbedingung und Randvergleich begründet."]),
    section("c-integral","Gebietsteilung und gekoppelte Dichte",[8],"8.dichte",
      "D=[0,3]×[0,1] vereinigt mit [0,1]×[1,2]. Beschreibe den Reihenfolgewechsel mit Teilung. Berechne Fläche und ∫∫_D(x+y). Separat p=(2/3)(x+2y) auf [0,1]²: Normierung, Momente und Cov. Separat: e^(−x²−y²) auf der ganzen Ebene integrieren, Ergebnis geteilt durch π.",
      [["Fläche D",4],["Integral über D",8],["Normierungsintegral p",1],["E[X]",5/9],["E[Y]",11/18],["E[XY]",1/3],["Cov",-1/162],["Gaußintegral 2D / π",1]],
      ["Horizontal: y∈[0,1],x∈[0,3] und y∈[1,2],x∈[0,1]. Vertikal bei x=1 teilen: x∈[0,1],y∈[0,2] und x∈[1,3],y∈[0,1]. Fläche 4, Integral 6+2=8.","p_X=(2/3)(x+1),p_Y=1/3+4y/3; E[X]=5/9,E[Y]=11/18,E[XY]=1/3,Cov=−1/162.","2π∫₀∞e^(−r²)rdr=π; 1D-Gaußintegral √π."],
      ["1 P: Skizze und Teilung bei 1; 1 P: beide Integrationsreihenfolgen korrekt beschrieben.","1 P: Randdichten samt Träger hergeleitet; 1 P: Polar-Jacobian und Grenzwert begründet."]),
  ]},
];
